### ISSUE TITLE
Add New Storage Location

### ISSUE THREAD

**Issue by tylerazfab** [briandorey/PartFinder#1]
I get the following error

"The sort order must be a number."

I have tried different numbers with the same result.

**Comment by briandorey** [comment]
Which page is this error on ?

**Comment by tylerazfab** [comment]
Dashboard > Admin > Add Storage Location

**Comment by briandorey** [comment]
Thank you for reporting this bug, I have fixed the code in https://github.com/briandorey/PartFinder/blob/master/partfinder/App_Code/Helpers.cs 
The error was caused by 
 public static bool TextBoxIsInt(TextBox key)
    {
        if (key.Text != null && key.Text.Length > 0)

It was not checking the length of the input correctly.

**Comment by tylerazfab** [comment]
Edited the code and works. Thanks!
