### ISSUE TITLE
Clearing Categories > Trying To Add New New Parts

### ISSUE THREAD

**Issue by tylerazfab** [briandorey/PartFinder#2]
Hello there,

I found another issue. Running the following SQL commands to clear the existing database

`DELETE FROM FootprintCategory`
`DELETE FROM PartCategory`

When you try to add another part I receive the following message after submitting.

> Your item has been deleted.

I have tried adding manufactures, footprint categories, etc. before adding a new part with no luck. The Total Parts counter does increase. If I re-run the original database.sql, those same parts that I tried to add, will populate.

I suspect it has something to do with the categories.

**Comment by briandorey** [comment]
Please can  you post a screen shot of the add part page before you save the information? 

The add part page should redirect to the view.aspx page with the parts details. 

The new part needs to have information in the Footprints, Manufacturers and Storage Location tables.

**Comment by tylerazfab** [comment]
You can close/delete this issue. 

`DELETE FROM FootprintCategory`
`DELETE FROM Footprint`
`DELETE FROM PartCategory`

I forgot to clear Footprint so it caused it to act funny. Sorry about the false flag.
